### ISSUE TITLE
Sidekiq 4 support?

### ISSUE THREAD

**Issue by psugihara** [NuckChorris/sidekiq-debounce#10]
Does this gem support Sidekiq 4?

Thanks!

**Comment by NuckChorris** [comment]
I haven't tested it since I haven't switched to Sidekiq 4 yet.  I'll add a build for that to the matrix and we'll find out!

**Comment by birchlore** [comment]
Any update?

**Comment by funtusov** [comment]
It seems that Sidekiq 4.0.2 was added to the build matrix and have tests passing: https://travis-ci.org/hummingbird-me/sidekiq-debounce

**Comment by ben-axnick** [comment]
Working with Sidekiq 4.2.9.

Seems like it would be plenty safe to close this issue out.

**Comment by NuckChorris** [comment]
As stated, we seem to be all green on Sidekiq 4 👌
